### ISSUE TITLE
Could not find dependency File[/etc/php5/cli/php.ini] for Package[php5-cli]

### ISSUE THREAD

**Issue by Wesseldr** [thias/puppet-php#18]
Hi,
I'm running into something unexpected.

I'm using Ubuntu 13.10 and when running the php::cli command it breaks.
The php.ini is not in /etc/php.ini so I gave the 'inifile' for the correct location.

``` puppet
class { 'php::cli':
  inifile => '/etc/php5/cli/php.ini'
}
```

However it still fails with

``` output
Error: Could not find dependency File[/etc/php5/cli/php.ini] for Package[php5-cli] at /tmp/vagrant-puppet-1/modules-0/php/manifests/cli.pp:16
```

However the file is there:

``` bash
# ls -lsa /etc/php5/cli/php.ini
68 -rw-r--r-- 1 root root 69593 Dec 11 20:25 /etc/php5/cli/php.ini
```

Is my lack of knowledge of puppet kicking me here (sorry for that) or did i found a little one :-)

Many thanks in advance,
             Wessel

**Comment by heskymatic** [comment]
I had the exact same issue. Thanks for the explanation. @thias

**Comment by heskymatic** [comment]
Hi @thias 

I checked again. Actually in a play from scratch, the folder `/etc/php5/cli` doesn't exist, so that it will complain `Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /etc/php5/cli/php.ini20150417-10564-itg7gf.lock at 117:/etc/puppet/modules/php/manifests/ini.pp`

Maybe we don't need the`    require => File[$inifile],` in `puppet-php/manifests/cli.pp`?

Any advice?
Thanks!
